config/routes.rb
Rails.application.routes.draw do
  resources :contact_us

  resources :users
  resources :trains
  post 'contact' => "home#contact"
  get 'contact' => "home#contact"
  post 'ticket_fare' => "home#ticket_fare"
  get 'index' => "home#index"
  get 'pnr_status' => "home#pnr_status"
  get 'stations' => "home#stations"
  get 'routes' => "home#routes"
  get 'ticket_fare' => "home#ticket_fare"

  root 'home#index'

end

app/models/contact_u.rb
class ContactU < ActiveRecord::Base
end

app/models/station.rb
class Station < ActiveRecord::Base

  def station_name
    "#{code} - #{name}"
  end

  def self.station_name(code)
    station = get_record(code)
    "#{station.try(:station_name)}"
  end

  def self.get_name(code)
    get_record(code).try(:name)
  end

  def self.get_record(code)
    find_by_code code
  end

  def self.get_stations
    if last.nil?
      @rail_in = RailIn.new(ERAILKEY)
      stations = @rail_in.stations
      store_stations(stations)
    end
    all
  end

  def self.store_stations(stations)
    transaction do
      stations.each do |station|
        Station.create!(station)
      end
    end
  end
end

app/models/train.rb
class Train < ActiveRecord::Base

  def train_name
    "#{train_no} - #{name}"
  end

  def self.train_name(code)
    station = get_record(code)
    "#{station.try(:train_name)}"
  end

  def self.get_trains
    if last.nil?
      transaction do
        path = Rails.root.to_s + "/trains.csv"
        CSV.read(path, headers:true).each do |train|
          Train.create!(train.to_hash)
        end
      end
    end
    all
  end

  def self.get_name(no)
    get_record(no).try(:name)
  end

  def self.get_record(no)
    find_by_train_no no
  end

end

app/models/user.rb
class User < ActiveRecord::Base

	def self.train_detail(train_no)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController
  before_action :set_contact_u, only: [:show, :edit, :update, :destroy]

  # GET /contact_us
  # GET /contact_us.json
  def index
    @title = "Contact Us"
    @contact_u = ContactU.new
  end

  # GET /contact_us/1
  # GET /contact_us/1.json
  def show
  end

  # GET /contact_us/new
  def new
    @contact_u = ContactU.new
  end

  # GET /contact_us/1/edit
  def edit
  end

  # POST /contact_us
  # POST /contact_us.json
  def create
    @contact_u = ContactU.new(contact_u_params)

    respond_to do |format|
      if @contact_u.save
        UserMailer.contact_us(@contact_u).deliver
        format.html { redirect_to :index, notice: 'Contact u was successfully created.' }
        format.json { render :show, status: :created, location: @contact_u }
      else
        format.html { render :new }
        format.json { render json: @contact_u.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_us/1
  # PATCH/PUT /contact_us/1.json
  def update
    respond_to do |format|
      if @contact_u.update(contact_u_params)
        format.html { redirect_to @contact_u, notice: 'Contact u was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact_u }
      else
        format.html { render :edit }
        format.json { render json: @contact_u.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_us/1
  # DELETE /contact_us/1.json
  def destroy
    @contact_u.destroy
    respond_to do |format|
      format.html { redirect_to contact_us_url, notice: 'Contact u was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_u
      @contact_u = ContactU.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_u_params
      params.require(:contact_u).permit(:name, :email, :message)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
before_filter :set_erail_key

  def pnr_status
    @title = "PNR Status"
    if params[:pnr_number]
      # 4404478884
      # 4104458537
      @pnr_status = @rail_in.pnr_status(params[:pnr_number])
    end
  end

  def stations
    @title = "Stations"
    @stations = Station.get_stations
    respond_to do |format|
      format.html { render :stations }
      # format.json { render :show, status: :created, location: @contact_u }
      format.json { render json: @stations.map {|s| { label: s.station_name, value: s.station_name, code: s.code, name: s.name }} }
    end
  end

  def ticket_fare
    @title = "Ticket Fare"
    @stations = Station.get_stations.limit(100)
    if params[:search]
      @date = params[:search][:date]
      @station_from = params[:search][:from]
      @station_to = params[:search][:to]
      p @trains = @rail_in.trains(@station_from, @station_to)
    elsif params[:train]
      @date = params[:train][:date]
      @train_no = params[:train][:train_no]
      @class_code = params[:commit]
      @from = params[:train][:from]
      @to = params[:train][:to]
      p "ticket_fare"
      p url = "http://api.erail.in/fare/?key=#{ERAILKEY}&trainno=#{@train_no}&stnfrom=#{@from}&stnto=#{@to}&age=AD&quota=GN&date=#{@date}&class=#{@class_code}"
      @fare = JSON.parse(RestClient.get(url))
    elsif params[:passenger]
      class_code = params[:class_code]
      passengers = params[:passenger]
      date = params[:date]
      # p @fare = @rail_in.fare(params[:train_no], params[:from], params[:to], "24", "GN", date, class_code)

      # http://api.erail.in/fare/?key=fd3ebf59-3ed8-424f-a99d-5cfad4337d94&trainno=12138&stnfrom=NDLS&stnto=CSTM&age=AD&quota=GN&date=22-FEB-2015&class=SL
      # http://api.erail.in/fare/?key=fd3ebf59-3ed8-424f-a99d-5cfad4337d94&trainno=12661&stnfrom=MSdd&stnto=TTLd&age=AD&quota=GN&class=SL&date=15-FEB-2015
      render :fare
      # {"status"=>"OK", "result"=>{"trainno"=>"12662", "type"=>nil, "from"=>"TTL", "to"=>"MS", "age"=>"24", "quota"=>"GN", "date"=>"05-Mar-15", "fare"=>[{"cls"=>"", "fare"=>0}]}}
    end
  end

  def routes
    @title = "Route"
    if params[:train_no]
      @routes = @rail_in.route(params[:train_no])
    end
  end

  private

  def set_erail_key
    @rail_in = RailIn.new(ERAILKEY)
  end

end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController

	def index
		@title = "Trains"
		@trains = Train.get_trains
	    respond_to do |format|
	      format.html { render :index }
	      # format.json { render :show, status: :created, location: @contact_u }
	      format.json { render json: @trains.map {|t| { label: t.train_name, value: t.train_name, train_no: t.train_no, name: t.name }} }
	    end

	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/application/_fare_details.html.haml
- if @fare["status"]=="OK"
  %table.tablesorter2
    %thead
      %th Date
      %th Train no
      %th Train name
      %th From
      %th To
    %tbody
      %tr
        %td= @date
        %td= @train_no
        %td= Train.get_name(@train_no)
        %td= Station.get_name(@fare["result"]["from"])
        %td= Station.get_name(@fare["result"]["to"])


  .fare_div
    %table{style: "width: 190px;margin: 0 auto;"}
      %thead{style: "background: red;color: white;"}
        %th{style: "width: 100px"} Class
        %th{style: "width: 100px"} Fare
      %tbody
        - @fare["result"]["fare"].each do |fare|
          %tr{style: "font-weight: bold;border: 1px solid red;"}
            %td{style: "width: 100px;text-align: center;"}= fare["cls"]
            %td{style: "width: 100px;text-align: center;"}= number_to_currency(fare["fare"], unit: "र")
- else
  %p= @fare["status"]

app/views/application/_footer.html.haml
/ FOOTER
#footer
  .footer-wrapper
    / footer-cols
    %ul#footer-cols
      %li
        %h6 About the IRCTC
        %p Indian Railway Catering and Tourism Corporation, is a subsidiary of the Indian Railways that handles the catering, tourism and online ticketing operations of the railways.
        %p
          Accumsan porttitor ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Tincidunt quis, accumsan porttitor,
          = succeed "." do
            %a{:href => "http://luiszuno.com"} luiszuno.com
      %li
        %h6 Awards and achievements
        %p Within a short span of its going online, it had become the largest and the fastest-growing e-commerce website in the Asia-Pacific region, with about six lakh registered users as of 2013.
        %p Some of the other awards won by Indian Railway Catering and Tourism Corporation are:
        %ul
          %li Awarded the National Tourism Award of Excellence by Ministry of Tourism, Govt. of India.
      %li
        #tweets.footer-col.tweet
          %h6 Awards
          %ul
            %li Awarded the National Award for E-Governance, 2007–08 jointly by Department of IT, Govt. of India and Govt. of Haryana.
            %li Awarded the Genius of the Web Award 2007 for being the "Best E-Governance PSU Site" by CNBC.
            %li Won National award for E-Governance for being "Best Citizen Centric Application" for the year 2007–08.
            %li Won the ICICI Bank Retail Excellence Award in 2005.
    / ENDS footer-cols
    #footer-glare
/ ENDS FOOTER
/ footer-bottom
#footer-bottom
  .bottom-wrapper
    #bottom-left
      \&copy; 2015 IRCTC.
    #bottom-right
      %ul#footer-nav
        %li
          %a{:href => trains_path} Trains
        %li
          %a{:href => stations_path} Stations
        %li
          %a{:href => routes_path} Route
          %li
            %a{:href => ticket_fare_path} Ticket Fare
/ ENDS footer-bottom

app/views/application/_front_slider.html.haml
/ Front slider
#front-slides
  .slides_container
    /
      .slide
        %a{:href => "http://www.luiszuno.com", :target => "blank"}
          %img{:alt => "pic", :height => "360", :src => "/assets/dummies/01.jpg", :width => "940"}/
        .caption Visit my site at luiszuno.com and get freebies each week
      .slide
        %a{:href => "http://themeforest.net/user/Ansimuz/portfolio?ref=ansimuz", :target => "blank"}
          %img{:alt => "pic", :height => "360", :src => "/assets/dummies/02.jpg", :width => "940"}/
        .caption Support the freebies buying premium themes at themeforest.com
    .slide
      %img{:alt => "pic", :height => "360", :src => "/assets/home.jpg", :width => "940"}/
      .caption Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est tristique senectus et netus et malesuada.
  #front-slides-cover
  / Headline
  #headline
    %h6 Indian Railway Catering and Tourism Corporation
  / ENDS Headline
/ ENDS Front slider

app/views/application/_nav_bar.html.haml
/ nav bar holder
#nav-bar-holder
  / Navigation
  %ul#nav.sf-menu
    %li{class: "#{'current-menu-item' if action_name=='index' and controller_name=='home'}"}
      %a{:href => root_path} Home
    %li{class: "#{'current-menu-item' if action_name=='index' and controller_name=='trains'}"}
      %a{:href => trains_path} Trains
    %li{class: "#{'current-menu-item' if action_name=='stations'}"}
      %a{:href => stations_path} Stations
    %li{class: "#{'current-menu-item' if action_name=='routes'}"}
      %a{:href => routes_path} Route
    %li{class: "#{'current-menu-item' if action_name=='pnr_status'}"}
      %a{:href => pnr_status_path} PNR Status
    %li{class: "#{'current-menu-item' if action_name=='ticket_fare'}"}
      %a{:href => ticket_fare_path} Ticket Fare
    %li{class: "#{'current-menu-item' if action_name=='contact'}"}
      %a{:href => contact_us_path} Contact Us
  / ENDS Navigation
  / Social
  %ul.social
    %li
      %a.poshytip.facebook{:href => "http://www.facebook.com", :title => "Become a fan"}
    %li
      %a.poshytip.twitter{:href => "http://www.twitter.com", :title => "Follow my tweets"}
    %li
      %a.poshytip.dribbble{:href => "http://www.dribbble.com", :title => "Working on..."}
  / ENDS Social
/ ENDS nav bar holder

app/views/application/_reel_slider.html.haml
/ Reel slider
#reel
  .slides_container
    .slide-box
      .box-container
        %img.box-icon{:alt => "pic", :src => "/assets/mono-icons/bargraph32.png"}/
        %h6 Now, cash on delivery 
        = succeed "You" do
          .box-divider
        can now book a rail ticket online and get it delivered at home. Initiating this "cash on delivery"(CoD) system rail ticketing, IRCTC is targeting those customers who are reluctant to use their credit or debit cards also those who don't have net-banking facility.
      .box-container
        %img.box-icon{:alt => "pic", :src => "/assets/mono-icons/boxupload32.png"}/
        %h6 'e-wallet' scheme
        = succeed "IRCTC" do
          .box-divider
        has launched e-wallet, a user-friendly scheme aimed at making purchase of e-tickets easier. The e-wallet is a rolling deposit scheme wherein the customers will have an account with the IRCTC and deposit money to be used in future for booking e-tickets from its website .
      .box-container
        %img.box-icon{:alt => "pic", :src => "/assets/mono-icons/article32.png"}/
        %h6 e-catering service
        = succeed "IRCTC" do
          .box-divider
        has started e-catering services for 76 trains, in its bid to provide quality food to passengers. Passengers can order food at www.ecatering.irctc.co.in or call the toll-free number 1800-1034-139 or 0120-4383892-99 to avail the facility, a senior IRCTC official said.
  %a.prev{:href => "#"}
  %a.next{:href => "#"}
/ ENDS Reel slider

app/views/application/_schedule_detail.html.haml
%p
  %span Date
  %span= @date
  %span From
  %span= Station.get_name(@from)
  %span To
  %span= Station.get_name(@to)

app/views/application/_search_train.html.haml
%form
  .form-group
    /%input#exampleInputEmail1.form-control{:placeholder => "From station", name: "search[from]", :type => "text", value: @station_from}
    /%input#exampleInputEmail1.form-control{:placeholder => "To station", name: "search[to]", :type => "text", value: @station_to}
    - if params[:search].present?
      - date =  params[:search][:date]
      - from = params[:search][:from]
      - to = params[:search][:to]
    %label Date
    %input{type: :text, name: "search[date]", id: "datepicker", value: date}
    %label{for: "datepicker"}
      %img{src: "/assets/calendar.png"}
    %input{name: "search[from]", type: :hidden, class: "from_station", value: from}
    %input{name: "search[to]", type: :hidden, class: "to_station", value: to}
    %label From
    %input{type: :text, class: "from_stations_inp", placeholder: "From Stations", value: Station.station_name(from)}
    %label To
    %input{type: :text, class: "to_stations_inp", placeholder: "To Stations", value: Station.station_name(to)}
  %button{:type => "submit"} Submit

app/views/contact_us/_form.html.haml
= form_for @contact_u do |f|
  - if @contact_u.errors.any?
    #error_explanation
      %h2= "#{pluralize(@contact_u.errors.count, "error")} prohibited this contact_u from being saved:"
      %ul
        - @contact_u.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name, required: true, placeholder: "Name"
  .field
    = f.label :email
    = f.text_field :email, required: true, placeholder: "Email"
  .field
    = f.label :message
    = f.text_area :message, required: true, placeholder: "Type your message here"
  .actions
    = f.submit 'Save'

app/views/contact_us/edit.html.haml
%h1 Editing contact_u

= render 'form'

= link_to 'Show', @contact_u
\|
= link_to 'Back', contact_us_path

app/views/contact_us/index.html.haml
= render "form"

app/views/contact_us/new.html.haml
%h1 New contact_u

= render 'form'

= link_to 'Back', contact_us_path

app/views/contact_us/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @contact_u.name
%p
  %b Email:
  = @contact_u.email
%p
  %b Message:
  = @contact_u.message

= link_to 'Edit', edit_contact_u_path(@contact_u)
\|
= link_to 'Back', contact_us_path

app/views/home/fare.html.haml
= render "fare_details"

app/views/home/index.html.haml
%ul.featured-posts
  %li
    %a.thumb{:href => "single.html", :title => "An image"}
      %img{:alt => "Post", :src => "/assets/train1.jpg", class: "feature_img"}
    .excerpt
      .heading>
        %a{:href => "single.html"} Trains
      This the place where you can get all available train lists easily and know the train number as well start station and end station.
  %li
    %a.thumb{:href => "single.html", :title => "An image"}
      %img{:alt => "Post", :src => "/assets/train2.jpg", class: "feature_img"}
    .excerpt
      .heading>
        %a{:href => "single.html"} Stations
      This the place where you can get all available station lists easily and know the station code.
  %li
    %a.thumb{:href => "single.html", :title => "An image"}
      %img{:alt => "Post", :src => "/assets/train3.jpg", class: "feature_img"}/
    .excerpt
      .heading>
        %a{:href => "single.html"} Route
      This the place where you can get Route for particular train and know the station arrival and departure time.
  /
    %li
      %a.thumb{:href => "single.html", :title => "An image"}
        %img{:alt => "Post", :src => "/assets/dummies/290x170.jpg"}/
      .excerpt
        .heading>
          %a{:href => "single.html"} Pellentesque habitant morbi
        Tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam. Donec eu libero sit amet quam egestas semper.
    %li
      %a.thumb{:href => "single.html", :title => "An image"}
        %img{:alt => "Post", :src => "/assets/dummies/290x170.jpg"}/
      .excerpt
        .heading>
          %a{:href => "single.html"} Pellentesque habitant morbi
        Tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam. Donec eu libero sit amet quam egestas semper.
    %li
      %a.thumb{:href => "single.html", :title => "An image"}
        %img{:alt => "Post", :src => "/assets/dummies/290x170.jpg"}/
      .excerpt
        .heading>
          %a{:href => "single.html"} Pellentesque habitant morbi
        Tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam. Donec eu libero sit amet quam egestas semper.
.clear

app/views/home/pnr_status.haml
%form
  .form-group
    %input#exampleInputEmail1.form-control{:placeholder => "PNR Number", name: :pnr_number, :type => "text", value: params[:pnr_number]}
  %button{:type => "submit"} Submit

- if @rail_in and @pnr_status
  - if @pnr_status["status"]=="OK"
    %table.table
      %thead
        %th Train number
        %th Train name
        %th Boarding Date
        %th From
        %th To
        %th Boarding point
        %th Class
      %tbody
        %tr
          %td= @pnr_status["result"]["trainno"]
          %td= @pnr_status["result"]["name"]
          %td= @pnr_status["result"]["journey"]
          %td= @pnr_status["result"]["from"]
          %td= @pnr_status["result"]["to"]
          %td= @pnr_status["result"]["from"]
          %td= @pnr_status["result"]["cls"]
    %table.table
      %thead
        %th{colspan: 3} Paassanger
        %th{colspan: 2} Booking Status 
        %th{colspan: 2} Current Status 
        - @pnr_status["result"]["passengers"].each_with_index do |passenger, index|
          %tr
            %td{colspan: 3}= "Passenger #{index+1}"
            %td{colspan: 2}= passenger["bookingstatus"]
            %td{colspan: 2}= passenger["currentstatus"]
        %tr
          %td{colspan: 3} Charting Status
          %td{colspan: 4}= @pnr_status["result"]["chart"]
  - else
    %p
      - if @pnr_status["error_message"]
        = @pnr_status["error_message"]
      - else
        = @pnr_status["status"]

app/views/home/routes.html.haml
%form
  .form-group
    %input{type: :hidden, class: "train_number_inp", name: :train_no, value: params[:train_no]}
    %input.train_inp{:placeholder => "Train number", :type => "text", value: Train.get_name(params[:train_no])}
  %button{:type => "submit"} Submit
- if @routes
  - if @routes["status"]=="OK"
    %h3= @routes["result"]["name"]
    %table.tablesorter
      %thead
        %th Train name
        %th Arrival time
        %th Departure time
        %th Day
      %tbody
        - @routes["result"]["route"].each_with_index do |route, index|
          - route["stn"].each_with_index do |stn, index|
            %tr
              %td= stn["name"]
              %td= stn["arr"]
              %td= stn["dep"]
              %td= stn["day"]
  - else
    %h3= @routes["error_message"]

app/views/home/station_lists.html.haml
%h2 Stations
- p @stations
%table.table.table-striped
  %thead
    %th #
    %th Code
    %th Name
  %tbody
    - @stations.each_with_index do |station, index|
      %tr
        %td= index + 1
        %td= station["code"]
        %td= station["name"]

app/views/home/stations.html.haml
%input.search{"data-column" => "all", :type => "search"}
  (Match any column)
%input.search{"data-column" => "1", :type => "search"}
  (Station code; Tiruttangal search... try "TTL")
%button.reset{:type => "button"} Reset Search
%table.tablesorter
  %thead
    %th #
    %th{"data-placeholder"=>"Station code"} Code
    %th Name
  %tbody
    - @stations.each_with_index do |station, index|
      %tr
        %td= index + 1
        %td= station.code
        %td= station.name

app/views/home/ticket_fare.html.haml
- if params[:train]
  /= render "schedule_detail"
- else
  = render "search_train"
- if @trains
  %table.tablesorter
    %thead
      %th #
      %th Train Number
      %th Train Name
      %th From
      %th Start Time
      %th To
      %th Arrival Time
      %th Travel Time
      %th Class
    %tbody
      - if @trains["status"]=="OK"
        - @trains["result"].each_with_index do |train, index|
          = form_for "train", method: :get do |f|
            - train_no = train["trainno"]
            %tr
              %td= index + 1
              %td
                %input{type: :hidden, name: "train[date]", value: @date}
                %input{type: :hidden, name: "train[train_no]", value: train["trainno"]}
                %input{type: :hidden, name: "train[from]", value: train["from"]}
                %input{type: :hidden, name: "train[to]", value: train["to"]}
                = train["trainno"]
              %td= train["name"]
              %td= train["fromname"]
              %td= train["dep"]
              %td= train["toname"]
              %td= train["arr"]
              %td= train["traveltime"]
              - if train["cls"]
                %td
                  - ticket_classes = train["cls"].split(" ")
                  -ticket_classes.each do |c| 
                    %button{name: :commit, type: :submit, value: c }= c
      - else
        %td{colspan: 5} Something went wrong

- if params[:train]
  = render "fare_details"
  /
    %h3 Passenger Details
    %form
      %input{type: :hidden, value: @train_no, name: :train_no}
      %input{type: :hidden, value: @from, name: :from}
      %input{type: :hidden, value: @to, name: :to}
      %input{type: :hidden, value: @class_code, name: :class_code}
      %input{type: :hidden, value: @date, name: :date}
      - 6.times.each do |i|
        %div
          %label Name
          %input{type: :text, name: "passenger[#{i}][name]"}
          %label Sex
          %select{name: "passenger[#{i}][sex]"}
            %option{value: :male} Male
            %option{value: :female} Female
          %label Age
          %input{type: :text, name: "passenger[#{i}][age]"}
      %button{type: :submit} Submit



app/views/users/_form.html.haml
= form_for @user, html: { class: "form form-horizontal user" } do |f|
  .form-group
    = f.label :username, class: 'control-label'
    .controls
      = f.text_field :username, class: 'form-control', required: true
    = error_span(@user[:username])
  .form-group
    = f.label :email, class: 'control-label'
    .controls
      = f.text_field :email, class: 'form-control', required: true
    = error_span(@user[:email])
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn btn-default'

app/views/users/index.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:username)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.id, user_path(user)
        %td= user.username
        %td= user.email
        %td=l user.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/users/show.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:username) + ':'
  %br
  = @user.username
%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @user.email


= link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'